### ISSUE TITLE
Add ansible verifier

### ISSUE THREAD

**Issue by bootswithdefer** [ansible/molecule#1493]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.6.4
  config file = /home/jldefer/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

```
molecule, version 2.18.1
```

Molecule installation method (one of): pip

Ansible installation method (one of): pip

# Desired Behavior
I would like a verifier that just runs a playbook (or series of playbooks) would let us test using ansible itself.  Similar to how goss/inspec run a verify.yml playbook, this would be a verifier that just runs arbitrary playbooks.

For example one could deploy a web server with Ansible then use the uri module to test that it's serving web pages.

**Comment by wilmardo** [comment]
I did this before switching to Goss by adding `post_tasks` to the converge playbook. 
Like this:
```yaml

---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-plex

  post_tasks:
    - name: Wait for Plex to succesfully restart
      wait_for:
        port: 32400

    - name: Test Plex webinterface
      uri:
        url: "http://{{ inventory_hostname }}:32400/web"

    - name: Wait for Tautulli to succesfully restart
      wait_for:
        port: 8181
      when: tautulli_install

    - name: Test Tautulli webinterface
      uri:
        url: "http://{{ inventory_hostname }}:8181/home"
      when: tautulli_install
```
