### ISSUE TITLE
Three or more layers of groups

### ISSUE THREAD

**Issue by DinMouMou** [ansible/molecule#1496]
# Issue Type

- Feature request

# Desired Behavior

I think molecule just support two layer of groups (group and children)? 
For example we have following inventory/architecture:
```
[group1]
host1
host2

[group2]
host3
host4

[group3]
host5
host6

[group4]
host7
host8

[group5:children]
group1
group2

[group6:children]
group3
group4

[group7:children]
group5
group6
```
So what I can do in molecule.yml is like following, wchih is quite confusing and may not work if the scenario is more complicated.
```
instance: host1
group: 
- group7
- group5
children: 
- group5
- group1
```

I think it would be better if molecule support more than two layers of group?

**Comment by lwm** [comment]
Hi there, I think this is already possible but your example isn't making sense since a group is a child of itself (group5)? Can you please clarify on that? The docs have the following example (and claim it is possible to make 'groups of groups' and it does look like you can go to some arbitrary depth):

```yaml
        platforms:
          - name: instance-1
            groups:
              - group1
              - group2
            children:
              - child_group1
```
