### ISSUE TITLE
Configuration of Dockerfile.j2 location

### ISSUE THREAD

**Issue by plasticrake** [ansible/molecule#1502]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.7.0
```

```
molecule, version 2.18.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I'd like to share the `Dockerfile.j2` file across scenarios / roles, like [defined in the docs here](https://molecule.readthedocs.io/en/latest/examples.html#sharing-across-scenarios)

I'm new to molecule, so help me if I misunderstand. Currently the default `docker/create.yml` does not allow you to change the location of the `Dockerfile.j2` (it is hard coded to the scenario directory, [here](https://github.com/metacloud/molecule/blob/25a9ee3ee0cd2eb880c94c9400b926686e75cab6/molecule/provisioner/ansible/playbooks/docker/create.yml#L23)), so in order to support this I'd need to use symlinks or my own custom `create.yml`, both I'd like to avoid.

I'm not sure the best place to define where to load the Dockerfile.j2 from, but with input on the design I can submit a pull request. Two options would be under `platforms`, or under `provisioner`.

```yaml
platforms:
  - name: instance
    image: debian:stable
    dockerfile: ../resources/Dockerfile.j2
```

```yaml
provisioner:
  name: ansible
  dockerfile: ../resources/Dockerfile.j2
```

Please let me know if I'm missing anything, or if what I'm trying to accomplish can be done another way. If wanted, I can submit a pull request. Thank you!

**Comment by retr0h** [comment]
Can you submit s pr to do the former?  Keeps it consistent w rest of molecule.

**Comment by wilmardo** [comment]
You could already specify `pre_build_image` if your image is pushed to a registry.

https://molecule.readthedocs.io/en/latest/configuration.html#docker

Use it like this:

```yaml
platforms:
  - name: Centos7
     image: lansible/centos:7
     pre_build_image: True
```

Then the run skips all the build steps and pulls the image from a registry. To me this seems far more elegant then sharing the Dockerfile.j2 in your situation. It also speeds up the testing since no more building is needed.

There still is a usecase for the sharing so feel free to open a PR, just adding my two cents for a different solution :)
