### ISSUE TITLE
Documentation for testing roles that require docker on all Operating Systems

### ISSUE THREAD

**Issue by shamsalmon** [ansible/molecule#1513]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.6.3
```

```
molecule, version 2.18.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

There should be documentation on how to do make a role that requires Docker-in-Docker work on every system. For my use case I could not socket mount docker because the role itself does volume mounting. My CI system would run the docker containers inside or docker correctly with the volume mount but to get that to work on MacOS there are modifications that need to be made to molecule.yml and the docker storage drive.

/etc/docker/daemon.json should use aufs (https://github.com/shamsalmon/ansible-role-docker-storage) and ran before the role that requires a docker volume mounts inside your molecule container.

Molecule.yaml should look like this
```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
```

I am not sure how best to contribute to documentation as this seems like a very specific use case but I wanted the information out there if someone else finds it useful.
