### ISSUE TITLE
Error vagrant.yml config with multiple instances

### ISSUE THREAD

**Issue by HaloGithub** [ansible/molecule#1519]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version

ansible 2.7.0
python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

```
molecule --version

molecule, version 2.18.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Here is my `molecule.yml` file:

```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance-1
    ansible_groups: master
    box: centos/7
    interfaces:
      - network_name: private_network
        ip: '192.168.33.11'
  - name: instance-2
    ansible_groups: slave
    box: centos/7
    interfaces:
      - network_name: private_network
        ip: '192.168.33.12'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
```

Here is generated `vagrant.yml` file:

```
# Molecule managed

---
config:
  options:
    ssh.insert_key: true
    synced_folder: false
instance:
  interfaces:
    - ip: 192.168.33.12
      network_name: private_network
  name: instance-2
  raw_config_args: null
platform:
  box: centos/7
  box_url: null
  box_version: null
provider:
  name: virtualbox
  options:
    cpus: 2
    memory: 512
  override_args: null
  raw_config_args: null
``` 

# Actual Behaviour (Bug report only)

In `molecule.yml`, I defined 2 instances, but generated `vagrant.yml` file only include the last instance. Everytime I want to `vagrant ssh` into the first instance, it failed since the error `vagrant.yml` file. 

By the way, I try to fix this problem, but when I debug molecule source code, the breakpoint in `VagrantClient` didn't pause. Can write a wiki about how to develop molecule? Or provide some information about how to debug molecule plugins or run molecule unit test. Thank you very much!
