### ISSUE TITLE
provider_raw_config_args are not applied. I cannot attach a second hard drive to a vagrant/virtualbox VM

### ISSUE THREAD

**Issue by pescobar** [ansible/molecule#1550]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.1
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

attach a second hard drive to a vagrant/virtualbox VM

# Actual Behaviour

I have tested that this Vagrantfile creates a new VM with a second drive attached. (I did this test using only vagrant outside of molecule)
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
     vb.customize ['createhd', '--filename', 'beegfsDisk.vdi', '--size', 20 * 1024]
     vb.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'beegfsDisk.vdi']
     vb.memory = "1024"
   end
end
```

Based on this I modified my config `molecule/default/molecule.yml` like this:

```yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  enabled: false
platforms:
  - name: centos7.5-vagrant
    box: centos/7
    # centos7.5 image
    # https://app.vagrantup.com/centos/boxes/7
    # https://blog.centos.org/2018/10/updated-centos-vagrant-images-available-v1809-01/
    box_version: "1809.01"
    cpus: 2
    memory: 4096
    provider_raw_config_args:
      - "customize ['createhd', '--filename', 'beegfsDisk.vdi', '--size', 50 * 1024]"
      - "customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'beegfsDisk.vdi']"
    groups:
      - cluster_beegfs_mgmt
      - cluster_beegfs_mds
      - cluster_beegfs_oss
      - cluster_beegfs_client
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      R: true
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests
  options:
    verbose: true
  lint:
    name: flake8
```

but still always that I try `molecule test` the booted vm doesn't include an extra hard drive. 

`molecule --debug` shows that `provider_raw_config_args` are readed but they are not passed to vagrant? This is the output of `Create molecule instances` in debug mode. Notice that `item` includes `provider_raw_config_args` but `invocation` says `"provider_raw_config_args": null, `

```
    changed: [localhost] => (item={'box': u'centos/7', 'box_version': u'1809.01', 'name': u'centos7.5-vagrant', 'groups': [u'cluster_beegfs_mgmt', u'cluster_beegfs_mds', u'cluster_beegfs_oss', u'cluster_beegfs_client'], 'provider_raw_config_args': [u"customize ['createhd', '--filename', 'beegfsDisk.vdi', '--size', 50 * 1024]", u"customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'beegfsDisk.vdi']"], 'memory': 4096, 'cpus': 2}) => {
        "Host": "centos7.5-vagrant", 
        "HostName": "127.0.0.1", 
        "IdentitiesOnly": "yes", 
        "IdentityFile": "/tmp/escobar/molecule/ansible-role-beegfs/default/.vagrant/machines/centos7.5-vagrant/virtualbox/private_key", 
        "LogLevel": "FATAL", 
        "PasswordAuthentication": "no", 
        "Port": "2222", 
        "StrictHostKeyChecking": "no", 
        "User": "vagrant", 
        "UserKnownHostsFile": "/dev/null", 
        "changed": true, 
        "invocation": {
            "module_args": {
                "config_options": {}, 
                "force_stop": false, 
                "instance_interfaces": [], 
                "instance_name": "centos7.5-vagrant", 
                "instance_raw_config_args": null, 
                "platform_box": "centos/7", 
                "platform_box_url": null, 
                "platform_box_version": "1809.01", 
                "provider_cpus": 2, 
                "provider_memory": 4096, 
                "provider_name": "virtualbox", 
                "provider_options": {}, 
                "provider_override_args": null, 
                "provider_raw_config_args": null, 
                "provision": false, 
                "state": "up"
            }
        }, 
        "item": {
            "box": "centos/7", 
            "box_version": "1809.01", 
            "cpus": 2, 
            "groups": [
                "cluster_beegfs_mgmt", 
                "cluster_beegfs_mds", 
                "cluster_beegfs_oss", 
                "cluster_beegfs_client"
            ], 
            "memory": 4096, 
            "name": "centos7.5-vagrant", 
            "provider_raw_config_args": [
                "customize ['createhd', '--filename', 'beegfsDisk.vdi', '--size', 50 * 1024]", 
                "customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'beegfsDisk.vdi']"
            ]
        }, 
        "log": "/tmp/escobar/molecule/ansible-role-beegfs/default/vagrant-centos7.5-vagrant.out"
    }
```

Is this a bug or am I doing something wrong? Reading the docs here https://molecule.readthedocs.io/en/latest/configuration.html#molecule-vagrant-module I think my `molecule.yml` config looks ok.
