### ISSUE TITLE
Delegated drive:"Could not resolve hostname"

### ISSUE THREAD

**Issue by robertdebock** [ansible/molecule#1582]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.1
  config file = None
  configured module search path = [u'/home/robertdb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:26:09) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

I'm [trying to setup a digitalocean scenario](https://github.com/robertdebock/ansible-role-bootstrap/tree/master/molecule/digitalocean) but can't get it to work.

I've based my code on [the documentation](https://molecule.readthedocs.io/en/latest/configuration.html#delegated) and [this issue report](https://github.com/ansible/molecule/issues/1292).

It must be a mistake I've made somewhere, just can't understand what's wrong. 

# Actual Behaviour

It looks like the populated inventory does not contain the molecule configured parameters:

molecule.yml snippet:
```
driver:
  name: delegated
  options:
    managed: yes
    ansible_connection_options:
      connection: ssh
      ansible_ssh_common_args: -F $MOLECULE_EPHEMERAL_DIRECTORY/ssh-config
```

The generated ansible_inventory.yml:
```
# Molecule managed

---
all:
  hosts:
    bootstrap-fedora: &id001 {}
  vars:
    molecule_ephemeral_directory: '{{ lookup(''env'', ''MOLECULE_EPHEMERAL_DIRECTORY'')
      }}'
    molecule_file: '{{ lookup(''env'', ''MOLECULE_FILE'') }}'
    molecule_instance_config: '{{ lookup(''env'', ''MOLECULE_INSTANCE_CONFIG'') }}'
    molecule_scenario_directory: '{{ lookup(''env'', ''MOLECULE_SCENARIO_DIRECTORY'')
      }}'
    molecule_yml: '{{ lookup(''file'', molecule_file) | molecule_from_yaml }}'
ungrouped:
  hosts:
    bootstrap-fedora: *id001
  vars: {}
```

I'm expecting to find a line in the ansible_inventory.yml:
```
      ansible_ssh_common_args: -F /some/path/to/ssh-config
```

But this line is no present, so Ansible does not know how to reach the node, resulting in:
```
    fatal: [bootstrap-fedora]: UNREACHABLE! => {
        "changed": false, 
        "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname bootstrap-fedora: Name or service not known\r\n", 
        "unreachable": true
    }
```
