### ISSUE TITLE
dockerfile option is innefective since image build still happens under `molecule_ephemeral_path`

### ISSUE THREAD

**Issue by danielkza** [ansible/molecule#1583]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.7.1
  config file = /home/danielkza/.ansible.cfg
  configured module search path = ['/home/danielkza/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/danielkza/cobli/deploy-gravitational-teleport/ansible/venv/lib/python3.6/site-packages/ansible
  executable location = /home/danielkza/cobli/deploy-gravitational-teleport/ansible/venv/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
molecule, version 2.19.0
```

# Desired Behavior

I have a scenario with multiple Docker containers. Some of them correspond to things I'm actually setting up with Ansible, and some are just external services needed for the tests. I want to use a custom Dockerfile to build the former (which is *different* from the Molecule dockerfile that installs the Ansible prerequisites).

So I have something like that in my config:

```
driver:
  name: docker
platforms:
  - name: etcd-1
    image: etcd
    dockerfile: Dockerfile-etcd

  - name: service-a
    # implicitly uses the Dockerfile.j2 template

  - name: service-b
    # implicitly uses the Dockerfile.j2 template
```

Actually running `molecule create` fails because the etcd build still happens inside the `molecule_ephemeral_dir`, and the Dockerfile obviously does not reside there (and is not copied there at all). The stacktrace is exceedingly verbose, but in short, Docker fails with:

`docker.errors.APIError: 500 Server Error: Internal Server Error (\"Cannot locate specified Dockerfile: ./Dockerfile-etcd\")

Molecule should set the image build context directory to the same path as the custom Dockerfile by default, or allow it to be specified manually.
