### ISSUE TITLE
Adding Custom Dockerfile is not working

### ISSUE THREAD

**Issue by anis016** [ansible/molecule#1617]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.2
  config file = None
  configured module search path = [u'/home/sayed/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sayed/ultra_patch/docker-hive-database/py2.7-venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/sayed/ultra_patch/docker-hive-database/py2.7-venv/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Given a user provided Dockerfile the `molecule test` should be able to run the Dockerfile and the tests is supposed to perform on that.

# Actual Behaviour

Followed this link for adding a custom Dockerfile: [Added ability to specify custom dockerfile](https://github.com/ansible/molecule/pull/409)
The custom Dockerfile is not picked while running `molecule test` command

1. The folder structure looks like below:

.
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── molecule
│   └── default
│       ├── Dockerfile                ### This is the custom Dockerfile added.
│       ├── Dockerfile.j2
│       ├── INSTALL.rst
│       ├── molecule.yml
│       ├── playbook.yml
│       ├── pytestdebug.log
│       └── tests
│           ├── __pycache__
│           │   └── test_default.cpython-27-PYTEST.pyc
│           ├── test_default.py
│           └── test_default.pyc
├── outputs
├── README.md
├── tasks
│   └── main.yml
└── vars
    └── main.yml

2. The custom Dockerfile is a simple Dockefile that prints a line:
Dockerfile
```
FROM busybox

CMD ["echo", "this is for docker"]
```

3. Modified the `molecule.yml` to include the custom Dockerfile as below 
```
docker:
  containers:
    - name: custom-docker
      image: anis016/custom-molecule
      image_version: latest
      dockerfile: '/home/sayed/ultra_patch/docker-hive-database/ansible-tests1/molecule/default/Dockerfile'
      build_image: true
```

output of running `molecule --debug test`: [molecule debug output](https://gist.github.com/anis016/d5e365f44c02c93e674e2f1d5cadbb4c)
