### ISSUE TITLE
Openstack configuration example is incorrect in documentation

### ISSUE THREAD

**Issue by tsmilam** [ansible/molecule#1628]
# Issue Type

- Bug report

The [Openstack configuration documentation](https://molecule.readthedocs.io/en/latest/configuration.html#openstack) example is incorrect where it's demonstrating SSH args. Trying to run it results in the following error:

```
--> Validating schema roles/bind/molecule/default/molecule.yml.
ERROR: Failed to validate.

{'driver': [{'ssh_connection_options': ['must be of list type']}]}
```

The example in the documentation should probably look like this:
```
driver:
  name: openstack
  ssh_connection_options:
    - -o ControlPath=~/.ansible/cp/%r@%h-%p
```
