### ISSUE TITLE
Check on docker registry password too restrictive

### ISSUE THREAD

**Issue by thertp** [ansible/molecule#1662]
# Issue Type

- Bug report

# Molecule and Ansible details

```
molecule, version 2.19.0
ansible 2.6.3
  config file = /home/rtp/.ansible.cfg
  configured module search path = [u'/home/rtp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

Detail any linters or test runners used:

I'm using vagrant on my system and docker for my local gitlab ci. For the gitlab-ci side, I'm using a container hosted by this gitlab server. To do this, I'm using two scenarii with only differences are the driver and platform used.

My molecule platforms setting for the ci job is:
```
platforms:
- name: instance
  image: ${CI_REGISTRY}/stretch/systemd:latest
  registry:
    url: https://${CI_REGISTRY}
    credentials:
      username: gitlab-ci-token
      password: $CI_JOB_TOKEN
```

# Desired Behavior

It would be easier if the regexp used to validate the password allows:
- environment variables with underscores
- syntax like ${CI_JOB_TOKEN:-invalidpassword}

# Actual Behaviour

- When running the scenario with the vagrant driver, I'm getting:
```
ERROR: Failed to validate.

{'platforms': [{0: [{'registry': [{'credentials': [{'password': ['null value not allowed']}]}]}]}]}
```

- If I create an environment variable, It now complains about the underscores :
```
ERROR: Failed to validate.

{'platforms': [{0: [{'registry': [{'credentials': [{'password': ["value does not match regex '^[{$]+[a-z0-9A-Z]+[}]*$'"]}]}]}]}]}
```
This one happens also when running the scenario on gitlab ci.
