### ISSUE TITLE
Can't make vagrant instances communicate with each other

### ISSUE THREAD

**Issue by gustavomcarmo** [ansible/molecule#1679]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.6
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

Vagrant instances able to communicate with each other.

# Actual Behaviour

molecule.yml: https://github.com/codeyourinfra/codeyourinfra/blob/master/unarchive_from_url_param/molecule/default/molecule.yml
```yml
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: repo
    box: codeyourinfra/repo
    instance_interfaces:
      - network_name: private_network
        ip: 192.168.33.10
  - name: server1
    box: ubuntu/bionic64
    instance_interfaces:
      - network_name: private_network
        ip: 192.168.33.20
    groups:
      - servers
  - name: server2
    box: ubuntu/bionic64
    instance_interfaces:
      - network_name: private_network
        ip: 192.168.33.30
    groups:
      - servers
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
```

Converge action execution output:
```
--> Action: 'converge'
    
    PLAY [Converge] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [server1]
    ok: [server2]
    
    TASK [unarchive_from_url_param : Create the target directory if it doesn't exist] ***
    changed: [server1]
    changed: [server2]
    
    TASK [unarchive_from_url_param : Install unzip] ********************************
    skipping: [server1]
    changed: [server2]
    
    TASK [unarchive_from_url_param : Unarchive from url] ***************************
    fatal: [server2]: FAILED! => {"changed": false, "msg": "Failure downloading http://192.168.33.10/server2.zip, Request failed: <urlopen error [Errno 113] No route to host>"}
    fatal: [server1]: FAILED! => {"changed": false, "msg": "Failure downloading http://192.168.33.10/server1.tar.gz, Request failed: <urlopen error [Errno 113] No route to host>"}
    
    PLAY RECAP *********************************************************************
    server1                    : ok=2    changed=1    unreachable=0    failed=1   
    server2                    : ok=3    changed=2    unreachable=0    failed=1
```
