### ISSUE TITLE
Openstack driver: Unclear instructions on overrides/configuration handling

### ISSUE THREAD

**Issue by johanssone** [ansible/molecule#1680]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.7.6
  config file = None
  configured module search path = [u'/home/ekan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ekan/dev/github/maas-venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/ekan/dev/github/maas-venv/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
molecule, version 2.19.0

```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Detail any linters or test runners used:
- yamllint
- testinfra
# Desired Behavior
I find it somewhat unclear which ansible/molecule settings that should be overridable from `molecule.yml` for the Openstack driver. 
Example:
```
platforms:
  - name: maas-single-1604
    image: Ubuntu 16.04 Xenial Xerus
    flavor: 1C-1GB-50GB
    networks: Default network
    ssh_user: ubuntu
    sshuser: ubuntu
   user: ubuntu
    groups:
      - maas
```
Above configuration snippet properly overrides `image` and `flavor` also default set in `create.yml`. Overriding `networks` and the three different tests for `user` does not seem to work. 

I would expect common variables such as which network to use in OpenStack project, and which remote user to run tests as, to be overridable. Alternatively, a reference to values that are overridable and which are not.

Changing values for `neutron_network_name` and `ssh_user` directly in `create.yml` resolves the issue, but I'm not sure this is the intended behavior..
create.yml:
```
---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  vars:
    *ssh_user: ubuntu*
    ssh_port: 22
....
    *neutron_network_name: Default network*
```
# Actual Behaviour
See ^
