### ISSUE TITLE
Idempotence fails when running script

### ISSUE THREAD

**Issue by xprazak2** [ansible/molecule#1709]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version

ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.pyenv/versions/3.7.2/envs/molecule_idempotence/lib/python3.7/site-packages/ansible
  executable location = /home/vagrant/.pyenv/versions/molecule_idempotence/bin/ansible
  python version = 3.7.2 (default, Jan 22 2019, 11:19:23) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
molecule, version 2.19.0
```

Molecule installation method:
- pip 

Ansible installation method:
- OS package

# Desired Behavior

I expect idempotence to pass when executing script that is idempotent with script module.

# Actual Behaviour
I need to run a script on a target host to retrieve and transform information needed for the tasks in my role, but when script module is used in role's tasks, the idempotence step fails regardless of what the script does. It can be completely empty or print a constant text to stdout, idempotence always fails.

I created a [repo](https://github.com/xprazak2/molecule_idempontence) with a minimal reproducer

**Comment by lwm** [comment]
Hi @xprazak2, in the interest of taming the backlog we have on this project, I'm going to close this off as I think this is an issue in your playbook, not in Molecule. It doesn't mean we cannot re-open this or continue to discuss :+1:. Thanks.

**Comment by xprazak2** [comment]
Thank you for promptly looking into this. I do not pass any args as I only retrieve the information from target host:

```yml
 - name: 'Get something from host'
   script: my-script.sh
   register: script_output
```

I found a different solution - using custom facts. It seems cleaner and passes idempotence:

```yml
- name: 'Create custom facts file'
  copy:
    src: my-script.sh
    dest: /etc/ansible/facts.d/my_facts.fact
    mode: 0755

- name: 'Re-run setup to use custom facts'
  setup: ~
```

**Comment by iNecas** [comment]
FYI this also works (and I would argue it's better way to deal with registered vars) (based on https://medium.com/@sbarnea/why-ansible-ignore-errors-is-evil-500fb6e81229)

```yml
 - name: 'Get something from host'
   script: my-script.sh
   register: script_output
   changed_when: false
   failed_when: false
```
