### ISSUE TITLE
Allow to pass extra hosts to the inventory

### ISSUE THREAD

**Issue by beenje** [ansible/molecule#1748]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.7.7
  config file = /Users/benjaminbertrand/.ansible.cfg
  configured module search path = [u'/Users/benjaminbertrand/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/benjaminbertrand/miniconda3/envs/molecule2/lib/python2.7/site-packages/ansible
  executable location = /Users/benjaminbertrand/miniconda3/envs/molecule2/bin/ansible
  python version = 2.7.15 | packaged by conda-forge | (default, Nov 28 2018, 14:39:28) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Molecule automatically generates the inventory based on the hosts defined under `platforms`.
I'd like the option to define extra hosts to be added to the inventory, not for provisioning but just to access variables from `hostvars[name]`.

We use a dynamic inventory and have several roles (for dhcp, dns...) that use variables from other hosts. Testing those roles with molecule requires to have extra hosts, groups and variables defined.

I couldn't find a way to do that today.
It would be nice if we could give a base inventory with some pre-defined hosts that molecule would then update, or maybe add a `extra_hosts` section directly in molecule.yml

**Comment by lwm** [comment]
Hey @beenje, interesting use case. This makes sense to me and I can see it being useful. 

Could you provide an example `extra_hosts` of what you would expect it to look like? Or we could add a key to the existing instance list, like, `some-well-named-key: True`. Not sure what that key might be named as. Do you have ideas for a nice API for this?

For now, I think you could try to use [add_host](https://docs.ansible.com/ansible/latest/modules/add_host_module.html) and [setup](https://docs.ansible.com/ansible/latest/modules/setup_module.html) modules in the `prepare.yml` to get your extra vars.

**Comment by beenje** [comment]
Thanks for the quick feedback!
I think it might be more flexible to just pass an inventory file. Something like:
```
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../../inventory/hosts
      group_vars: ../../../inventory/group_vars/
      host_vars: ../../../inventory/host_vars/
```
Molecule would add the instances defined in molecule.yml to this inventory.
Of course those hosts would have to be ignored during create/converge/destroy.

So it's maybe easier to add a key as suggested:
```
platforms:
  - name: instance
    managed: false
```

`managed` would be `true` by default.

I think I'll try to play around see if I can get one of those 2 options to work.

**Comment by beenje** [comment]
I did a few tests and I think that adding the following shouldn't be too difficult:
```
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../../inventory/hosts
      group_vars: ../../../inventory/group_vars/
      host_vars: ../../../inventory/host_vars/
```

I didn't know but you can pass a directory as inventory and Ansible will automatically merge the [multiple inventory sources](https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html#using-inventory-directories-and-multiple-inventory-sources)!
So by always passing a directory to the ansible-playbook command during converge, it's easy to add another inventory file or even a dynamic script next to the ansible_inventory.yml file.

There is nothing to modify for create/destroy because they are looping on `molecule_yml.platforms`.

Will try to submit a PR but I have issues running the test suite. Is it possible to run it on OSX?
tox fails to compile lxc-python2.
