### ISSUE TITLE
exposed_ports should accept integers when validating molecule.yml schema

### ISSUE THREAD

**Issue by zeitounator** [ansible/molecule#1781]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version

ansible 2.7.8
  config file = None
  configured module search path = ['/home/olcla/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
molecule, version 2.19.1.dev139
```

Molecule installation method (one of):

-  sudo pip install git+https://github.com/ansible/molecule

Ansible installation method (one of):

- pip

# Desired Behavior

As: a standard molecule user

Given: this molecule.yml extract
```yaml
 platforms:                                                                                                                                                                    
   - name: instance                                                                                                                                                            
     image: centos:7                                                                                                                                                           
     exposed_ports:                                                                                                                                                            
         - 9900/tcp                                                                                                                                                            
         - "9901/tcp"                                                                                                                                                          
         - 9902/udp                                                                                                                                                            
         - "9903/udp"                                                                                                                                                          
         - 9904                                                                                                                                                                
         - "9905" 
```
When: I run `molecule lint`

Then: The command validates the schema of molecule.yml and exit without errors

# Actual Behaviour
```
user@host$ molecule lint
--> Validating schema /home/user/dev/my_test_role/molecule/default/molecule.yml.
ERROR: Failed to validate.

{'platforms': [{0: [{'exposed_ports': [{4: ['must be of string type']}]}]}]}
```
`exposed_ports` should accept a list of integers or strings (integer should automatically be casted to strings).
