### ISSUE TITLE
Dealing with delegated tasks

### ISSUE THREAD

**Issue by mmartinello** [ansible/molecule#1856]
I have several tasks which implements delegate_to declaration to run commands on hosts different than the one the play is running on.

I think I should run the test on two different hosts (I'm using the docker driver) and pass a custom inventory file to tests, but I'm not really sure how I could do this.

Could you help me, please?

**Comment by decentral1se** [comment]
Hi @mmartinello,

> I think I should run the test on two different hosts (I'm using the docker driver) and pass a custom inventory file to tests, but I'm not really sure how I could do this.

Can you clarify what you mean by 'test' here? The `molecule converge` (ansible running tasks) part or the `molecule verify` (testinfra, goss, inspec) part?

**Comment by mmartinello** [comment]
Hi @decentral1se, thank you for your answer.

> Can you clarify what you mean by 'test' here? The `molecule converge` (ansible running tasks) part or the `molecule verify` (testinfra, goss, inspec) part?

I'm developing an Ansible role for adding a new host to an existing Icinga2 instance.
To add a new satellite host to an Icinga2 master node you need to execute some commands on both master node and new satellite.

For this reason my role executes some tasks on the Ansible playlist host which I pass to the `ansible-playbook`, others are executed on the Icinga2 master node (declared in a variable) using the `delegate_to` parameter into the Ansible task.

**For example:**

```
    - name: Setup Icinga zones
      template:
        src: ../templates/icinga/endpoint-zones.conf.j2
        dest: /etc/icinga2/zones.conf
        owner: root
        group: root
        mode: 0644

    - name: Generate a new key and CSR for new satellite on icinga server
      shell: cd /tmp && icinga2 pki new-cert --cn {{ inventory_hostname }} --key /tmp/{{ inventory_hostname }}.key --csr /tmp/{{ inventory_hostname }}.csr
      delegate_to:  "{{ icinga2_master_host }}"
      when: icinga_satellite.stat.exists == False
```

The first task is executed on the current inventory host, the second is executed on `{{ icinga2_master_host }}`.

I am wondering how I can write a Molecule test to test these two tasks (I mean both `molecule converge` and `molecule verify` steps).

I think I need two different Docker instances to test these tasks with Molecule, because I need to simulate both the master node and the satellite. I can't execute both tasks on the same node because I need two different Icinga2 configurations.

How this could be done?
