### ISSUE TITLE
Molecule idempotency fails with yum

### ISSUE THREAD

**Issue by LibreBeats** [ansible/molecule#1860]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.7.6
molecule, version 2.19.0
python version = 3.6.7
```

Molecule installation method (one of):

- source
- pip [x]

Ansible installation method (one of):

- source
- pip
- OS package [x]

Detail any linters or test runners used:

# Desired Behavior

Idempotency test should be okay because packages state is present.

# Actual Behaviour
Idempotency fails because "package is already installed"

```- name: Install prerequisites
  yum:
    name: ["@^Development tools", "binutils", "autoconf", "flex", "bison", "libjpeg-devel"]
    state: present #Tried also with "installed"
  tags:
    - prereqs
    - yum
```
molecule --debug test (on idempotency section)

```
fatal: [Centos]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "installroot": "/",
            "list": null,
            "name": [
                "@^Development tools",
                "binutils",
                "autoconf",
                "flex",
                "bison",
                "libjpeg-devel"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "installed",
            "update_cache": false,
            "update_only": false,
            "use_backend": "auto",
            "validate_certs": true
        }
    },
    "msg": "Error: Nothing to do\n",
    "rc": 1,
    "results": [
        "binutils-2.27-34.base.el7.x86_64 providing binutils is already installed",
        "autoconf-2.69-11.el7.noarch providing autoconf is already installed",
        "flex-2.5.37-6.el7.x86_64 providing flex is already installed",
        "bison-3.0.4-2.el7.x86_64 providing bison is already installed",
        "libjpeg-turbo-devel-1.2.90-6.el7.x86_64 providing libjpeg-devel is already installed",
        "Loaded plugins: fastestmirror, ovl\nLoading mirror speeds from cached hostfile\n * base: mirror.airenetworks.es\n * extras: mirror.gadix.com\n * updates: mirror.airenetworks.es\nGroup Development tools does not exist.\n"
    ]
}
```

molecule.yml

```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: Centos
    image: centos:7
  - name: Debian
    image: debian:stretch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
```
