### ISSUE TITLE
Git capability to perform galaxy installs of github releases

### ISSUE THREAD

**Issue by sandal-maker** [ansible/molecule#1907]
# Issue Type

- Feature request

# Molecule and Ansible details

I've a requirements.yml file as below.
```yml
---
- src: https://github.com/wtanaka/ansible-role-gcloud-sdk
  version: master
  name: gcloud-sdk
```

And I've a molecule file as below.
```yml
---
dependency:
  name: galaxy
  options:
    role-file: ansible/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:18.04
provisioner:
  name: ansible
  playbooks:
    converge: ../../ansible/playbook.yml
  lint:
    name: ansible-lint
verifier:
  name: inspec
  directory: ../../tests/
  lint:
    name: rubocop
```

I'm running molecule in docker as below.
```bash
docker run --rm \
  -v $PWD:/build-run-tools-image \
  -w /build-run-tools-image \
  -v /var/run/docker.sock:/var/run/docker.sock \
  quay.io/ansible/molecule:2.20 \
  molecule test
```

# Actual behavior
```text
--> Action: 'dependency'
 [WARNING]: - gcloud-sdk was NOT installed successfully: could not find/use
git, it is required to continue with installing
https://github.com/wtanaka/ansible-role-gcloud-sdk
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
An error occurred during the test sequence action: 'dependency'. Cleaning up.
```

# Desired Behavior

Dependency installed successfully.

If git was available within the container then we'd be able to perform molecule tests without hassle.

Cheers.
@sandal-maker
