### ISSUE TITLE
Mystery value for ansible_ssh_common_args in ansible_inventory.yml

### ISSUE THREAD

**Issue by lamchakchan** [ansible/molecule#2005]
## Version

```
molecule --version
molecule, version 2.16.0
```

## Description
I'm utilizing an `openstack` driver in my scenario.  I'm attempting to override a key property for `ansible_ssh_common_args`.  I've added an entry to use `-o ProxyCommand ...` in the `molecule.yml` file but when I run Converge, my setting for that property is not captured.  The files generated in `/tmp/.../group_vars/all` shows my inventory settings.  But the inventory file generated in `/tmp/.../ansible_inventory.yml` does not.

### Partial `molecule.yml`
```
dependency:
  name: galaxy
# Controls the SSH connectivity to VM's provisioned in the test suite
driver:
  name: openstack
  # ssh_connection_options:
  #   - -o StrictHostKeyChecking=no
  #   - -o UserKnownHostsFile=/dev/null
  ssh_user: ubuntu

...

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        hello: world
        ansible_ssh_private_key_file: >-
          {{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key
        # ansible_ssh_common_args: "bleh"
        ansible_ssh_common_args: >-
          -o ProxyCommand='ssh {{ jump_host_key | default("") }}
          {{ jump_host_options | default("") }} -W %h:%p
          ubuntu@{{ hostvars["${OS_USERNAME}-molecule-tn-svc-orchestrate-bastion"].ansible_host }}'
        jump_host_key: >-
          -i "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
        jump_host_options: >-
          -o StrictHostKeyChecking={{ lookup(
...
```

### `/tmp/.../group_vars/all`
```
(tn-svc-orchestrate) ➜  default cat group_vars/all 
# Molecule managed

---
ansible_ssh_common_args: -o ProxyCommand='ssh {{ jump_host_key | default("") }} {{
  jump_host_options | default("") }} -W %h:%p ubuntu@{{ hostvars["e658121-molecule-tn-svc-orchestrate-bastion"].ansible_host
  }}'
ansible_ssh_private_key_file: '{{ lookup(''env'', ''MOLECULE_EPHEMERAL_DIRECTORY'')
  }}/ssh_key'
hello: world
jump_host_key: -i "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
jump_host_options: -o StrictHostKeyChecking={{ lookup('config', 'HOST_KEY_CHECKING')
  }} -o UserKnownHostsFile=/dev/null
```

### `/tmp/.../ansible_inventory.yml`
```
# Molecule managed

---
all:
  hosts:
    e658121-molecule-tn-svc-orchestrate-bastion: &id001
      ansible_host: 10.98.225.159
      ansible_port: 22
      ansible_private_key_file: /var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default/ssh_key
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no
      ansible_user: ubuntu
      connection: ssh
    e658121-molecule-tn-svc-orchestrate-svc1: &id003
      ansible_host: 10.99.64.132
      ansible_port: 22
      ansible_private_key_file: /var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default/ssh_key
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no
      ansible_user: ubuntu
      connection: ssh
    e658121-molecule-tn-svc-orchestrate-svc2: &id004
      ansible_host: 10.99.65.132
      ansible_port: 22
      ansible_private_key_file: /var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default/ssh_key
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no
      ansible_user: ubuntu
      connection: ssh
  vars: &id002
    molecule_ephemeral_directory: '{{ lookup(''env'', ''MOLECULE_EPHEMERAL_DIRECTORY'')
      }}'
    molecule_file: '{{ lookup(''env'', ''MOLECULE_FILE'') }}'
    molecule_instance_config: '{{ lookup(''env'', ''MOLECULE_INSTANCE_CONFIG'') }}'
    molecule_scenario_directory: '{{ lookup(''env'', ''MOLECULE_SCENARIO_DIRECTORY'')
      }}'
    molecule_yml: '{{ lookup(''file'', molecule_file) | molecule_from_yaml }}'
bastion:
  hosts:
    e658121-molecule-tn-svc-orchestrate-bastion: *id001
  vars: *id002
svc:
  hosts:
    e658121-molecule-tn-svc-orchestrate-svc1: *id003
    e658121-molecule-tn-svc-orchestrate-svc2: *id004
  vars:
    molecule_ephemeral_directory: '{{ lookup(''env'', ''MOLECULE_EPHEMERAL_DIRECTORY'')
      }}'
    molecule_file: '{{ lookup(''env'', ''MOLECULE_FILE'') }}'
    molecule_instance_config: '{{ lookup(''env'', ''MOLECULE_INSTANCE_CONFIG'') }}'
    molecule_scenario_directory: '{{ lookup(''env'', ''MOLECULE_SCENARIO_DIRECTORY'')
      }}'
    molecule_yml: '{{ lookup(''file'', molecule_file) | molecule_from_yaml }}'
ungrouped:
  vars: {}
```

### Scenario `playbook.yml`
```
---
- name: Converge (test)
  hosts: svc
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ hostvars[inventory_hostname] }}"
```

### Scenario Result
```
    PLAY [Converge (test)] *********************************************************
    
    TASK [debug] *******************************************************************
    ok: [e658121-molecule-tn-svc-orchestrate-svc1] => {
        "msg": {
            "ansible_check_mode": false, 
            "ansible_diff_mode": false, 
            "ansible_facts": {}, 
            "ansible_forks": 5, 
            "ansible_host": "10.99.64.132", 
            "ansible_inventory_sources": [
                "/var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default/ansible_inventory.yml"
            ], 
            "ansible_playbook_python": "/Users/lchan/.local/share/virtualenvs/tn-svc-orchestrate-RiCpnRo-/bin/python2.7", 
            "ansible_port": 22, 
            "ansible_private_key_file": "/var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default/ssh_key", 
            "ansible_run_tags": [
                "all"
            ], 
            "ansible_skip_tags": [
                "molecule-notest", 
                "notest"
            ], 
            "ansible_ssh_common_args": "-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no", 
            "ansible_ssh_private_key_file": "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key", 
            "ansible_user": "ubuntu", 
            "ansible_verbosity": 0, 
            "ansible_version": {
                "full": "2.7.8", 
                "major": 2, 
                "minor": 7, 
                "revision": 8, 
                "string": "2.7.8"
            }, 
            "connection": "ssh", 
            "group_names": [
                "svc"
            ], 
            "groups": {
                "all": [
                    "e658121-molecule-tn-svc-orchestrate-svc1", 
                    "e658121-molecule-tn-svc-orchestrate-svc2", 
                    "e658121-molecule-tn-svc-orchestrate-bastion"
                ], 
                "bastion": [
                    "e658121-molecule-tn-svc-orchestrate-bastion"
                ], 
                "svc": [
                    "e658121-molecule-tn-svc-orchestrate-svc1", 
                    "e658121-molecule-tn-svc-orchestrate-svc2"
                ], 
                "ungrouped": []
            }, 
            "hello": "world", 
            "inventory_dir": "/var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default", 
            "inventory_file": "/var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default/ansible_inventory.yml", 
            "inventory_hostname": "e658121-molecule-tn-svc-orchestrate-svc1", 
            "inventory_hostname_short": "e658121-molecule-tn-svc-orchestrate-svc1", 
            "jump_host_key": "-i \"{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key\"", 
            "jump_host_options": "-o StrictHostKeyChecking={{ lookup('config', 'HOST_KEY_CHECKING') }} -o UserKnownHostsFile=/dev/null", 
            "molecule_ephemeral_directory": "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}", 
            "molecule_file": "{{ lookup('env', 'MOLECULE_FILE') }}", 
            "molecule_instance_config": "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}", 
            "molecule_scenario_directory": "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}", 
            "molecule_yml": "{{ lookup('file', molecule_file) | molecule_from_yaml }}", 
            "playbook_dir": "/Users/lchan/Projects/tn-svc-orchestrate/molecule/default"
        }
    }
    ok: [e658121-molecule-tn-svc-orchestrate-svc2] => {
        "msg": {
            "ansible_check_mode": false, 
            "ansible_diff_mode": false, 
            "ansible_facts": {}, 
            "ansible_forks": 5, 
            "ansible_host": "10.99.65.132", 
            "ansible_inventory_sources": [
                "/var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default/ansible_inventory.yml"
            ], 
            "ansible_playbook_python": "/Users/lchan/.local/share/virtualenvs/tn-svc-orchestrate-RiCpnRo-/bin/python2.7", 
            "ansible_port": 22, 
            "ansible_private_key_file": "/var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default/ssh_key", 
            "ansible_run_tags": [
                "all"
            ], 
            "ansible_skip_tags": [
                "molecule-notest", 
                "notest"
            ], 
            "ansible_ssh_common_args": "-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no", 
            "ansible_ssh_private_key_file": "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key", 
            "ansible_user": "ubuntu", 
            "ansible_verbosity": 0, 
            "ansible_version": {
                "full": "2.7.8", 
                "major": 2, 
                "minor": 7, 
                "revision": 8, 
                "string": "2.7.8"
            }, 
            "connection": "ssh", 
            "group_names": [
                "svc"
            ], 
            "groups": {
                "all": [
                    "e658121-molecule-tn-svc-orchestrate-svc1", 
                    "e658121-molecule-tn-svc-orchestrate-svc2", 
                    "e658121-molecule-tn-svc-orchestrate-bastion"
                ], 
                "bastion": [
                    "e658121-molecule-tn-svc-orchestrate-bastion"
                ], 
                "svc": [
                    "e658121-molecule-tn-svc-orchestrate-svc1", 
                    "e658121-molecule-tn-svc-orchestrate-svc2"
                ], 
                "ungrouped": []
            }, 
            "hello": "world", 
            "inventory_dir": "/var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default", 
            "inventory_file": "/var/folders/hq/_fz8fhwd32g55vnlw1ckwhd40000gp/T/molecule/tn-svc-orchestrate/default/ansible_inventory.yml", 
            "inventory_hostname": "e658121-molecule-tn-svc-orchestrate-svc2", 
            "inventory_hostname_short": "e658121-molecule-tn-svc-orchestrate-svc2", 
            "jump_host_key": "-i \"{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key\"", 
            "jump_host_options": "-o StrictHostKeyChecking={{ lookup('config', 'HOST_KEY_CHECKING') }} -o UserKnownHostsFile=/dev/null", 
            "molecule_ephemeral_directory": "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}", 
            "molecule_file": "{{ lookup('env', 'MOLECULE_FILE') }}", 
            "molecule_instance_config": "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}", 
            "molecule_scenario_directory": "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}", 
            "molecule_yml": "{{ lookup('file', molecule_file) | molecule_from_yaml }}", 
            "playbook_dir": "/Users/lchan/Projects/tn-svc-orchestrate/molecule/default"
        }
    }
```
