### ISSUE TITLE
Molecule should expose values from molecule.yml as ansible host variables

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2097]
It would be very useful to be able define variables that are platform specific in molecule.yml which are later exposed to playbook execution.

At this moment these are accesible only via `molecule_yml.platforms` list of dictionaries and extracting data out of it requires parsing this with ansible.

Instead we should make use we make the expose host specific ones for each platform, so parsing is no needed.

**Comment by MarkusTeufelberger** [comment]
You mean like this?

```
provisioner:
  name: ansible
  # CoreOS has a non-standard interpreter location
  inventory:
    host_vars:
      coreos-alpha:
        ansible_python_interpreter: /opt/bin/python
      coreos-beta:
        ansible_python_interpreter: /opt/bin/python
      coreos-stable:
        ansible_python_interpreter: /opt/bin/python
```

**Comment by gabyfulchic** [comment]
I think he is talking about the var scope into molecule.yml.  
  
When you define a docker_host in paltform side, and you reach the provisionner part in the same molecule.yml, molecule has already forgot the docker_host vars.  
So it will execute playbook locally when it has created containers remotly.  
(I can reproduce this with remote docker host, you will have a UNREACHABLE error in the converge part)   
 
To dodge this, you have to set var docker_host properly in the molecule.yml and to launch molecule test with ENV VARS too :  
```bash
DOCKER_HOST=tototot.com DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/cert/path/tototot molecule test
```

**Comment by beargiles** [comment]
Pinging this since I have a similar request. But I want to take a step back first.

Where should each stage (create, prepare, destroy, etc.) get its information? I think we can make a strong argument that create.yml and destroy.yml should get all of the information it needs from the 'platforms'. There may be information provided by the 'provisioner' but it should accessed indirectly. E.g., as 'hostvars'.

I also think that those properties should be something that makes sense as an hostvar, e.g., the location of other servers if we're creating multiple instances in our tests. I wouldn't think to put something like a list of users to be added in 'prepare' in it.

It turns out that I can get what I want for a specific host using a simple play:

```yml
    - ansible.builtin.set_fact:
        platform_facts: '{{ molecule_yml | to_json | from_json | community.general.json_query(platform_name_query) }}'
      vars:
        platform_name_query: "platforms[?name=='{{ inventory_hostname }}']"
```

but this isn't going to obvious to most people. I don't know if it's possible to provide this automatically, like 'inventory_hostname', the best that's possible is

```yml
   '{{ platform_facts[inventory_hostname].... }}'
```

but in any case we should document that snippet so people **can** access the respective 'platform' information if desired.

**Comment by beargiles** [comment]
Small correction:

```yml
    - ansible.builtin.set_fact:
        platform_facts: '{{ platform_facts_list[0] }}'
      vars:
        platform_name_query: "platforms[?name=='{{ inventory_hostname }}']"
        platform_facts_list: '{{ molecule_yml | to_json | from_json | community.general.json_query(platform_name_query) }}'
```
