### ISSUE TITLE
The Podman driver crashes

### ISSUE THREAD

**Issue by it-praktyk** [ansible/molecule#2158]
# Issue Type

- Bug report

```
ansible 2.8.1
  config file = None
  configured module search path = ['/home/<user_name>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<user_name>/Python-virtualenv/ansible-2.8.1/lib/python3.7/site-packages/ansible
  executable location = /home/<user_name>/Python-virtualenv/ansible-2.8.1/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

molecule, version 2.22rc3
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

The command `molecule test` will be executed successfully when the driver is set to `podman`.

# Actual Behaviour

The molecule.yml file content
```
---
dependency:
  name: galaxy
driver:
  name: podman
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    pull: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
```

The executed command
```
MOLECULE_NO_LOG=no molecule --debug test
```

The partial output

```
TASK [Build an Ansible compatible image] ***************************************
    task path: /home/<user_name>/Python-virtualenv/ansible-2.8.1/lib/python3.7/site-packages/molecule/provisioner/ansible/playbooks/podman/create.yml:40
    fatal: [localhost]: FAILED! => {
        "msg": "The conditional check 'platforms.changed or podman_images.results | map(attribute='images') | select('equalto', []) | list | count >= 0' failed. The error was: error while evaluating conditional (platforms.changed or podman_images.results | map(attribute='images') | select('equalto', []) | list | count >= 0): 'dict object' has no attribute 'images'\n\nThe error appears to be in '/home/<user_name>/Python-virtualenv/ansible-2.8.1/lib/python3.7/site-packages/molecule/provisioner/ansible/playbooks/podman/create.yml': line 40, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Build an Ansible compatible image\n      ^ here\n"
    }
```

The full output available as [the gist](https://gist.github.com/it-praktyk/97c81315581dc2609b90c898c800ffa8).
