### ISSUE TITLE
EC2 AMI Filtering based on Owner and Name (glob) Fully Documented

### ISSUE THREAD

**Issue by sblack4** [ansible/molecule#2237]
# Issue Type

- Bug report

# Molecule and Ansible details
```
ansible --version && molecule --version                                                                                                          

ansible 2.8.1
  config file = None
  configured module search path = ['/Users/sblack/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Detail any linters or test runners used:
- `yamlint`
- `ansible-lint`

# Desired Behavior
The [ec2 configuration docs](https://molecule.readthedocs.io/en/stable/configuration.html#ec2) give an example of selecting the image ID via `image_owner` and `image_name` but this behavior does not work "out of the box" in molecule. 

Example from docs:
```
driver:
  name: ec2
platforms:
  - name: instance
    image_owner: 099720109477
    image_name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190320
    instance_type: t2.micro
    vpc_subnet_id: subnet-1cb17175
```

It seems that in order for this to work one would need to add a task to look up the image id. I'm attempting to do so with the [ec2_ami_facts](https://docs.ansible.com/ansible/latest/modules/ec2_ami_facts_module.html#ec2-ami-facts-module) module.

I was wondering if this was already documented somewhere. If so a link to it in the documentation would be helpful. 

# Actual Behaviour

Resulting Bug (path partially redacted and lines wrapped for readability): 
```
    TASK [Create molecule instance(s)] *********************************************
    task path: **************************/jetty/molecule/default/create.yml:62
    fatal: [localhost]: FAILED! => {
        "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'image'

The error appears to be in '**************************/jetty/molecule/default/create.yml': line 62, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Create molecule instance(s)
      ^ here
"
    }
```

**Comment by sblack4** [comment]
I've gotten the bit to get the image ID which can be reached by `latest_image.image_id`. 

```
    - name: Get AMI ID from owner and name
      ec2_ami_facts:
        owners: "{{ item.image_owner }}"
        filters:
          name: "{{ item.image_name }}"
      register: ami_facts
      with_items: "{{ molecule_yml.platforms }}"

    - name: Get latest image from list of images
      set_fact: 
        latest_image: "{{ ami_facts.results[0].images | sort(attribute='creation_date', reverse=true) | first }}"
```
