### ISSUE TITLE
Recursive evaluation of shell variables does not work in molecule.yml

### ISSUE THREAD

**Issue by phibid** [ansible/molecule#2250]
Hi,

From the molecule documentation (https://molecule.readthedocs.io/en/stable/configuration.html), I can see that extended shell-style feature can be used in molecule.yml :

> Both` $VARIABLE and ${VARIABLE} syntax are supported. Extended shell-style features, such as ${VARIABLE-default} and ${VARIABLE:-default} are also supported.

And indeed, this is working :

```
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: "${CI_PROJECT_DIR:-/home/my_user}/ansible/group_vars"
      host_vars: "${CI_PROJECT_DIR:-/home/my_user}/ansible/host_vars"
```
Result :
```
--> Inventory /home/my_user/ansible/group_vars linked to /tmp/my_user/molecule/xymon_client/default/inventory/group_vars
--> Inventory /home/my_user/ansible/host_vars linked to /tmp/my_user/molecule/xymon_client/default/inventory/host_vars
```
However trying to evaluate another variable is not working. For example :

```
  inventory:
    links:
      group_vars: "${CI_PROJECT_DIR:-$HOME}/ansible/group_vars"
      host_vars: "${CI_PROJECT_DIR:-$HOME}/ansible/host_vars"
```
Is not working, value is not replaced :

```
ERROR: The source path '/home/my_user/roles/xymon_client/molecule/default/$HOME/ansible/group_vars' does not exist.
An error occurred during the test sequence action: 'lint'. Cleaning up.
ERROR: The source path '/home/my_user/roles/xymon_client/molecule/default/$HOME/ansible/group_vars' does not exist.
```

Is there a trick and do I miss something or is this not supported ?
