### ISSUE TITLE
Use build.args instead of buildargs in molecule.yml

### ISSUE THREAD

**Issue by phibid** [ansible/molecule#2262]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.8.2
  config file = /home/my_user/.ansible.cfg
  configured module search path = [u'/home/my_user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
molecule, version 3.0a1.dev3+gaa438bb
```

Molecule installation method:source
Ansible installation method: OS package

I need to specify some proxy parameters in molecule.yml as showed below

```
platforms:
  - name: instance
    image: centos:7
    buildargs:
      http_proxy: http://XX.YY.ZZ.WW:8080
      https_proxy: http://XX.YY.ZZ.WW:8080
```

This is perfectly working, however I have a warning while executing the molecule scenario :

```
 [WARNING]: Please specify build.args instead of buildargs. The buildargs
option has been renamed and will be removed in Ansible 2.12.
```

Would it be possible to adapt molecule to have build.args to be used ?

Thanks !
