### ISSUE TITLE
Molecule is not linting role

### ISSUE THREAD

**Issue by Dhawos** [ansible/molecule#2455]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version

ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
molecule, version 2.22
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):

- OS package

Detail any linters or test runners used:

```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: redhat-8
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: inspec
  lint:
    name: rubocop
    enabled: true
```

# Desired Behavior

Molecule would lint all task/handlers/meta from the role (this is the behavior obtained with molecule 2.19)

```
Examining /clamav/molecule/default/playbook.yml of type playbook
Examining /clamav/tasks/main.yml of type tasks
Examining /clamav/handlers/main.yml of type handlers
Examining /clamav/meta/main.yml of type meta
```

# Actual Behaviour

Molecule only lints the converge playbook and not the role

```
Examining /clamav/molecule/default/playbook.yml of type playbook
```
I noticed that environment variables were not set when it does not work :

```
DEBUG: ANSIBLE ENVIRONMENT
--- {}
```

When running with molecule 2.19, the Ansible environment variables are set and the linting works as expected.

I've played with the sources a bit and it seems this line is what is causing the issue :

**Version 2.22 :**
https://github.com/ansible/molecule/blob/a339ce2ecc38959065192c38110f2af46f07ac73/molecule/provisioner/lint/ansible_lint.py#L60

I tried with the line from previous versions and it worked again :

**Version 2.20 :**
https://github.com/ansible/molecule/blob/99e03ea192e19aba0a969e205980b55adae98456/molecule/provisioner/lint/ansible_lint.py#L107
