### ISSUE TITLE
instance_raw_config_args vm.provision ignored

### ISSUE THREAD

**Issue by VladAdGad** [ansible/molecule#3041]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.10.4
  config file = None
  configured module search path = ['/home/vlad/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vlad/.local/lib/python3.8/site-packages/ansible
  executable location = /home/vlad/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
molecule 3.2.2 using python 3.8 
    ansible:2.10.4
    delegated:3.2.2 from molecule
    vagrant:0.6.1 from molecule_vagrant
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):

- OS package

# Desired Behavior
I want to install desktop environment on Ubuntu 20.04 using
```
instance_raw_config_args:
  - 'vm.provision :shell, path: "${MOLECULE_PROJECT_DIRECTORY}/../../environment/scripts/install_gnome_desktop_ubuntu.sh"'
```
Script looks like:
```
#!/usr/bin/env --split-string=bash -eux

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install --yes tasksel
tasksel install ubuntu-desktop
``

# Actual Behaviour
No output at all even using --debug
Nothing happen no GUI. But when I run it manually everything works as expected. I done it using prepare.yml but it looks more like workaround

**Comment by apatard** [comment]
Maybe I'm missing something ... did you try something like (note the change of quotes) that ? :
```
- "vm.provision :shell, path: '${MOLECULE_PROJECT_DIRECTORY}/../../environment/scripts/install_gnome_desktop_ubuntu.sh'"
```

**Comment by LanceZeligman-KR** [comment]
I'm also seeing this issue while using inline, example

```
platforms:
  - name: sles11
    box: wvera/sles11sp4
    instance_raw_config_args:
      - "vm.provision :shell, inline: 'sudo /usr/sbin/useradd usera'"
      - "vm.provision :shell, inline: 'sudo /usr/sbin/useradd userb'"
      - "vm.provision :shell, inline: 'sudo /usr/sbin/useradd userc'"
      - "vm.provision :shell, inline: 'sudo /usr/sbin/useradd userd'"
      - "vm.provision :shell, inline: 'sudo /usr/sbin/usermod -A userc groupa'"
```
