### ISSUE TITLE
Switch to a single unified playbook for testing an entire scenario

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#3918]
Instead of having separated playbooks for each scenario step, we should be able to write an entire scenario as a single playbook. Here is an incomplete example on how it should look:

```yaml
---
- name: cleanup
  hosts: localhost
  gather_facts: false
  tasks:
     - name: Cleanup
       debug:
         msg: "Doing cleanup"
     - name: Foo
       standalone_module1: {}
  tags:
    - cleanup

- name: prepare
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Prepare
      debug:
        msg: "Doing prepare"

    - name: Add new host to tests group
      ansible.builtin.add_host:
        name: 127.0.0.1
        groups: test_group

- name: converge
  hosts: test_group # <-- this should now contain one host, but it does not
  gather_facts: false
  tasks:
     - name: converge
       debug:
         msg: "Doing converge"

- name: destroy
  hosts: localhost
  gather_facts: false
  tasks:
     - name: Destroy
       debug:
         msg: "Doing destroy"
```

When executed it will look like:
```
ssbarnea@m1: ~/c/a/101 main ⚡
$ ansible-playbook  tests/molecule/scenario1/converge.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [cleanup] ****************************************************************************************************************************************

TASK [Cleanup] ****************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Doing cleanup"
}

TASK [Foo] ********************************************************************************************************************************************
ok: [localhost]

PLAY [prepare] ****************************************************************************************************************************************

TASK [Prepare] ****************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Doing prepare"
}

TASK [Add new host to tests group] ********************************************************************************************************************
[WARNING]: A duplicate localhost-like entry was found (127.0.0.1). First found localhost was localhost
changed: [localhost]

PLAY [converge] ***************************************************************************************************************************************

TASK [converge] ***************************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": "Doing converge"
}

PLAY [destroy] ****************************************************************************************************************************************

TASK [Destroy] ****************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Doing destroy"
}

PLAY RECAP ********************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
localhost                  : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Molecule can make use of Ansible tag selection in order to skip specific steps when a single step command is asked by the user, so only a single play from the file would be executed.

This proposed change would allow us to write multiple scenarios inside a single folder and make it much easier to manage functional tests (scenarios), also enabling users to just use ansible to run them if they want, molecule being more than a facilitator that provides shorted command line options.
