### ISSUE TITLE
testinfra 9.0.0 use the same ssh connection as molecule/ansible… which can lead to wrong environment variables

### ISSUE THREAD

**Issue by tchernomax** [ansible/molecule#4066]
### Prerequisites

- [X] This was not already reported in the past (duplicate check)
- [X] It does reproduce it with code from main branch (latest unreleased version)
- [X] I include a minimal example for reproducing the bug
- [X] The bug is not trivial, as for those a direct pull-request is preferred
- [X] Running `pip check` does not report any conflicts
- [X] I was able to reproduce the issue on a different machine
- [X] The issue is not specific to any driver other than 'default' one

### Environment

```
molecule 5.1.0 using python 3.9
    ansible:2.14.9
    delegated:5.1.0 from molecule
    ec2:0.4 from molecule_ec2
```

### What happened

```
cat molecule/default/molecule.yml
…
verifier:
  name: testinfra
  options:
    verbose: true
    sudo: true
```

```
cat molecule/default/tests/test_default.py
…
def test_locales(host):
    locale_ = host.check_output("locale")
    assert "LANG=fr_FR.UTF-8" in locale_
    assert "LC_MESSAGES=en_US.UTF-8" in locale_
```

`molecule verify` report failure at first… then 60s or so later, the verify is ok.

This is because testinfra use the same ssh connection from ansible, which was created before ansible/molecule change the locales on the host.
60s later, the ssh persistent connection expire and testinfra use a new ssh connection with new environment (with the good locales).

What I did to bypass the problem:
```
cat molecule/default/molecule.yml
…
verifier:
  name: testinfra
  options:
    verbose: true
    sudo: true
  env:
    ANSIBLE_SSH_EXTRA_ARGS: '-o ControlPath=/tmp/testinfra_cp_%h-%p-%r'
```
