### ISSUE TITLE
MOLECULE_REPORT is not generating html report when mentioned in molecule.yml as per docs

### ISSUE THREAD

**Issue by ABHISHEK-SINHA10** [ansible/molecule#4081]
### Prerequisites

- [X] This was not already reported in the past (duplicate check)
- [X] It does reproduce it with code from main branch (latest unreleased version)
- [X] I include a minimal example for reproducing the bug
- [X] The bug is not trivial, as for those a direct pull-request is preferred
- [X] Running `pip check` does not report any conflicts
- [X] I was able to reproduce the issue on a different machine
- [X] The issue is not specific to any driver other than 'default' one

### Environment

molecule 6.0.2 using python 3.11 
    ansible:2.16.0
    azure:23.5.0 from molecule_plugins
    containers:23.5.0 from molecule_plugins requiring collections: ansible.posix>=1.3.0 community.docker>=1.9.1 containers.podman>=1.8.1
    default:6.0.2 from molecule
    docker:23.5.0 from molecule_plugins requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0
    ec2:23.5.0 from molecule_plugins
    gce:23.5.0 from molecule_plugins requiring collections: google.cloud>=1.0.2 community.crypto>=1.8.0
    podman:23.5.0 from molecule_plugins requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:23.5.0 from molecule_plugins

### What happened

As per molecule docs:  https://ansible.readthedocs.io/projects/molecule/configuration/#molecule.interpolation.Interpolator

If we mention MOLECULE_REPORT in molecule.yml, it's not generating html report.

### Reproducing example

```yml
---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    volumes:
      - /tmp:/tmpcl
provisioner:
  name: ansible
  env:
    MOLECULE_REPORT: 'molecule_report'
```
