### ISSUE TITLE
Molecule instance inherits all groups from inventory

### ISSUE THREAD

**Issue by Nebucatnetzer** [ansible/molecule#4150]
### Prerequisites

- [X] This was not already reported in the past (duplicate check)
- [X] It does reproduce it with code from main branch (latest unreleased version)
- [X] I include a minimal example for reproducing the bug
- [X] The bug is not trivial, as for those a direct pull-request is preferred
- [X] Running `pip check` does not report any conflicts
- [X] I was able to reproduce the issue on a different machine
- [X] The issue is not specific to any driver other than 'default' one

### Environment

```
molecule 24.2.0 using python 3.10
    ansible:2.16.2
    azure:23.5.3 from molecule_plugins
    containers:23.5.3 from molecule_plugins requiring collections: ansible.posix>=1.3.0 community.docker>=1.9.1 containers.podman>=1.8.1
    default:24.2.0 from molecule
    docker:23.5.3 from molecule_plugins requiring collections: community.docker>=3.4.11 ansible.posix>=1.4.0
    ec2:23.5.3 from molecule_plugins
    gce:23.5.3 from molecule_plugins requiring collections: google.cloud>=1.0.2 community.crypto>=1.8.0
    openstack:23.5.3 from molecule_plugins requiring collections: openstack.cloud>=2.1.0
    podman:23.5.3 from molecule_plugins requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:23.5.3 from molecule_plugins
```

### What happened

I have the following base-config, I expect it to just use the hosts in the inventory files for variable lookup and the instance having the `molecule` group assigned.

However for some reason the instance inherited all groups from the inventory, despite not even being mentioned in those files.
We have multiple inventory files split into development, integration and production and for molecule tests I might need any of the hosts present in those files to test the various paths a role can take.

```
---
driver:
  name: podman
role_name_check: 1
platforms:
  - name: instance
    image: quay.io/ansible/ubuntu2204-test-container:main
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - molecule
provisioner:
  name: ansible
  inventory:
    links:
      hosts: "../../../../inventories/"
      group_vars: "../../../../inventories/group_vars"
      host_vars: "../../../../inventories/host_vars"
```
