### ISSUE TITLE
Regarding Ansible Testing For Linux, Mac and Windows

### ISSUE THREAD

**Issue by mavsravikiran** [ansible/molecule#4249]
### Prerequisites

- [X] This was not already reported in the past (duplicate check)
- [X] It does reproduce it with code from main branch (latest unreleased version)
- [X] I include a minimal example for reproducing the bug
- [X] The bug is not trivial, as for those a direct pull-request is preferred
- [X] Running `pip check` does not report any conflicts
- [X] I was able to reproduce the issue on a different machine
- [X] The issue is not specific to any driver other than 'default' one

### Environment

I am trying to use the molecule on Windows, Linux and MacOS as well

### What happened

#  Description

- I am using ansible automation to install softwares like maven, node ,java, Terraform etc in both Windows and WSL(Linux)
- We are planning some automated testing for Windows, WSL and even for MacOS using Github Actions
- We are providing installation of softwares like node, terraform, java, python etc

# Scripting

-  Actually i am trying to implement for one of the sample role `maven` and below are the code blocks for Reference

 **For Windows**
```
- name: Windows - Install Maven
  command: "{{ powershell_path }} {{ windows_environment_variables }} choco upgrade {{ item.name }} --version {{ item.version }} --no-progress --allow-downgrade -y"
  retries: 5
  delay: 10
  register: result
  until: result is success
  loop:
    - { name: maven, version: "{{ maven_version }}" }

- name: Windows - Copy Maven settings.xml file
  copy:
    src: settings.xml
    dest: "{{ maven_windows_settings_path }}"
    mode: "644"
```

**For WSL**

```
---
- name: WSL - Add Maven plugin in asdf
  shell: "bash -lic 'source {{ wsl_bashrc_path }} && asdf plugin add maven'"
  become: true
  become_user: "{{ ansible_env.SUDO_USER }}"
  become_method: su
  retries: 5
  delay: 10
  register: result
  until: result is success
  failed_when: result.rc != 0 and result.rc != 2

- name: WSL - Install Maven
  shell: "bash -lic 'source {{ wsl_bashrc_path }} && asdf install maven {{ maven_version }}'"
  become: true
  become_user: "{{ ansible_env.SUDO_USER }}"
  become_method: su
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: WSL - Set global maven version
  shell: "bash -lic 'source {{ wsl_bashrc_path }} && asdf global maven {{ maven_version }}'"
  become: true
  become_user: "{{ ansible_env.SUDO_USER }}"
  become_method: su

- name: WSL - Copy Maven settings.xml file
  copy:
    src: settings.xml
    dest: "{{ maven_wsl_settings_path }}"
    mode: "644"
  become: true
  become_user: "{{ ansible_env.SUDO_USER }}"
  become_method: su

```

# Requirement 

- We are planning to have some testing for role level using molecule for the Windows, WSL, Macos using Github Actions
- Using Molecule how can we have the script at role level. need script for that would be more helpful

# Ask / Help

- Does the molecule would be a better choice for doing the functional and integration at role level?
- If that is possible need some script how to do at each role and Need to define Github Actions Workflow to include all the roles for testing the workflow

Please kindly help on this and quick support is much Appreciated 👍 

### Reproducing example

```yml
I have attached the content in above box
```
