### ISSUE TITLE
Task with include_role does not use external role's molecule default variables

### ISSUE THREAD

**Issue by dubmarm** [ansible/molecule#4387]
### Prerequisites

- [x] This was not already reported in the past (duplicate check)
- [x] It does reproduce it with code from main branch (latest unreleased version)
- [x] I include a minimal example for reproducing the bug
- [x] The bug is not trivial, as for those a direct pull-request is preferred
- [x] Running `pip check` does not report any conflicts
- [x] I was able to reproduce the issue on a different machine
- [x] The issue is not specific to any driver other than 'default' one

### Environment

```log
❯ molecule --version
[DEPRECATION WARNING]: DEFAULT_GATHER_SUBSET option, the module_defaults
keyword is a more generic version and can apply to all calls to the
M(ansible.builtin.gather_facts) or M(ansible.builtin.setup) actions, use
module_defaults instead. This feature will be removed from ansible-core in
version 2.18. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
molecule 24.9.0 using python 3.11
    ansible:2.16.13
    azure:23.6.1.dev3 from molecule_plugins
    containers:23.6.1.dev3 from molecule_plugins requiring collections: ansible.posix>=1.3.0 community.docker>=1.9.1 containers.podman>=1.8.1
    default:24.9.0 from molecule
    docker:23.6.1.dev3 from molecule_plugins requiring collections: community.docker>=3.10.2 ansible.posix>=1.4.0
    ec2:23.6.1.dev3 from molecule_plugins
    gce:23.6.1.dev3 from molecule_plugins requiring collections: google.cloud>=1.0.2 community.crypto>=1.8.0
    openstack:23.6.1.dev3 from molecule_plugins requiring collections: openstack.cloud>=2.1.0
    podman:23.6.1.dev3 from molecule_plugins requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:23.6.1.dev3 from molecule_plugins
```

### What happened

I've recently updated my molecule and ansible environment from `2.12`. In the past I was able to `include_role` and when I did `molecule test` the included role would load the included role's `molecule/default/group_vars/all.yml`. It would seem with these new version of molecule the loading of external molecule vars is no longer implied.

```yaml
# Role A
# role_a/tasks/test.yml
- name: Setup Role B
  ansible.builtin.include_role:
    name: role_b

- name: Get test.log contents; I expect it to be "bar"
  ansible.builtin.shell: cat /tmp/test.log
```

```yaml
# Role B
# role_b/defaults/role_b.yml
foo: 'derp'
```

```yaml
# Role B
# role_b/molecule/default/group_vars/all/role_b.yml
foo: 'bar'
```

```yaml
# Role B
# role_b/tasks/test.yml
- name: Create test file.
  ansible.builtin.copy:
    content: "{{ foo }}"
    dest: /tmp/test.log
```

The end result is that `/tmp/test.log` will read `derp` and NOT `bar`. If this isn't a bug then I can't seem to find the `history` when this behavior moved.

What do I need to do to get `role_b/molecule/default/group_vars/all/role_b.yml` registered when running molecule on `role_a`?

### Reproducing example

```yml

```
