### ISSUE TITLE
Confusing ansible provisioner doc

### ISSUE THREAD

**Issue by bitozoid** [ansible/molecule#4392]
I think that `hosts` is not a valid keyword for provisioner.

Maybe the author meant something like:

``` yaml
    provisioner:
      name: ansible
      inventory:
        hosts:
          all:
            hosts:
              ignored:
                 important: this host is ignored
        links:
          hosts: ../../../inventory/hosts
```

Otherwise it is a bit confusing.
