### ISSUE TITLE
Parameter arg documentation pulled into help string

### ISSUE THREAD

**Issue by Qalthos** [ansible/molecule#4396]
### Prerequisites

- [x] This was not already reported in the past (duplicate check)
- [x] It does reproduce it with code from main branch (latest unreleased version)
- [x] I include a minimal example for reproducing the bug
- [x] The bug is not trivial, as for those a direct pull-request is preferred
- [x] Running `pip check` does not report any conflicts
- [x] I was able to reproduce the issue on a different machine
- [x] The issue is not specific to any driver other than 'default' one

### Environment

25.2.0

### What happened

Since adding argument docs to molecule commands to appease pydoclint, these have been pulled unformatted into the click help output. This is expected, as it lives in the docstring, but unwanted, as it is unhelpful to the user

### Reproducing example

```yml
`molecule test -h`:


Usage: molecule test [OPTIONS] [ANSIBLE_ARGS]...

  Test (dependency, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup,
  destroy).

  Args:     ctx: Click context object holding commandline arguments.     scenario_name: Name of the scenario to
  target.     exclude: Name of the scenarios to avoid targeting.     driver_name: Name of the driver to use.
  __all: Whether molecule should target scenario_name or all scenarios.     destroy: The destroy strategy to use.
  parallel: Whether the scenario(s) should be run in parallel mode.     ansible_args: Arguments to forward to
  Ansible.     platform_name: Name of the platform to use.
```
